### ISSUE TITLE
Wiring 

### ISSUE THREAD

**Issue by Carlin75** [mercix/CTC2ESP#1]
Hi could you show how you wired the 2 MAX3232?
I'm not sure how to connect all to the ecologic.

/Carl

**Comment by mercix** [comment]
Hi Carl,

I have added the pinout .png to main branch, and i have edited the readme to include it.
Sorry for the delay, heating season started today for me.

BR

**Comment by Carlin75** [comment]
Great! 
Now perhaps I can monitor my ecoair.
Next step is connecting my ecologic to my burner for "spetsvärme"

But the second sparkfun isn't necessary?
Tusen tack😁

**Comment by mercix** [comment]
No problem, good luck! 

Nope with sparkfun you can utilize two different rs-232 channels, i used different rs-232<->uart modules before which could handle only one channel. Therefore it´s written two modules. 

Ingen fara ;)
